#spring.application.name=mortgage-app
spring:
  application:
    name: mortgage-app
  datasource:
    url: jdbc:mysql://localhost:3306/mort_account_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: AWSjob123#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


